//! Per-interface `vtable_index` Rust shim — fixture-specific stop-gap (T0.C.7).
//!
//! Why this file exists:
//! Upstream uniffi 0.29.5 does NOT emit per-callback-interface
//! `uniffi_<ns>_callback_<iface>_vtable_index(method) -> u32` exports. The
//! Kotlin/Wasm binding template
//! (`crates/gobley-uniffi-bindgen/src/templates/wasm-js/CallbackInterfaceImpl.kt`)
//! declares one `external fun __gobley_vtable_index_<iface>(method: Int): Int`
//! per callback interface and routes it through `globalThis.__gobleyRustExports`.
//! Without this shim crate side-loaded into the cdylib, those Kotlin externals
//! resolve to `undefined` at runtime and the first callback dispatch traps.
//!
//! Long-term plan (NOT this commit): synthesize these exports in
//! `gobley-wasm-transformer` post-process by walking the
//! `gobley_callbacks.<name>` import section. That makes the bindings work for
//! any consumer crate without per-fixture hand-written Rust. The hand-written
//! shim here proves the pipeline shape works end-to-end against the coverall
//! fixture. Tracked in `crates/gobley-uniffi-bindgen/docs/T0-kotlin-wasm-design.md`
//! Decision 3.
//!
//! Constraints baked into this file:
//!   * Gating happens at the `mod wasm_vtable_shim;` site in `lib.rs` via
//!     `#[cfg(target_arch = "wasm32")]`. JVM/Native cdylib builds therefore
//!     never see these symbols (linker would fail to resolve the
//!     `gobley_callbacks.*` imports — those only exist in the wasm world).
//!     A redundant inner `#![cfg(...)]` would warn under
//!     `clippy::duplicated_attributes`; we rely on the parent module's gate
//!     alone.
//!   * Method order MUST match the Kotlin template's `vtable_methods.iter()`
//!     iteration order, which mirrors UDL declaration order. uniffi's
//!     `CallbackInterface::vtable_methods()` walks `methods()` in source order
//!     (see `uniffi_bindgen-0.29.5/src/interface/callbacks.rs`). For
//!     `Getters` and `NodeTrait` the UDL order is fixed at
//!     `tests/uniffi/coverall/src/coverall.udl:254` and `:269`.
//!   * Method index `methods.len()` is reserved for `uniffi_free` (see
//!     `CallbackInterfaceImpl.kt`'s `register()` implementation).
//!   * `extern "C" fn` items are placed in `__indirect_function_table` by
//!     wasm-ld only if their address is observed somewhere in the binary
//!     (T0.C.1 spike, "Surprise: linker reorders imports" — see
//!     `crates/gobley-wasm-vtable-spike/src/lib.rs:64-65`). The
//!     `#[used] static CALLBACKS_*: [CallbackFn; N]` arrays serve that role.
//!     Their concrete table index is NOT baked in — `vtable_index` returns
//!     the runtime cast of the function pointer, which on wasm32 is the
//!     table index by definition (spike file:73-81).
//!
//! Why hand-written rather than generated by `build.rs`:
//! `build.rs` would need to parse the UDL or read uniffi metadata to discover
//! the callback interfaces. That's the same engineering as Option 2 (proper
//! transformer-based synthesis) without the cross-fixture payoff. We pay the
//! per-fixture cost only here, only for T0.C.7's verification gate.
//!
//! Known cascading gap (handled by T0.C.7.C / T0.C.7.D, NOT this task):
//! The `extern "C"` import declarations below elide actual argument lists
//! (declared as `fn name()`). wasm-ld emits the imports with the literal
//! `() -> ()` signature into the wasm module type section. That signature
//! WILL mismatch the real Kotlin `@JsExport public fun gobley_callback_*`
//! signatures at JS instantiation time — the wasm engine validates each
//! import against the host-provided function. Resolving the mismatch
//! requires either (a) declaring the full per-method signatures here
//! (mirroring uniffi's FFI-callback lowering: `uniffiHandle: u64`,
//! lifted args, `uniffi_out_return: *mut T`, `uniffi_call_status: *mut UniffiRustCallStatus`)
//! or (b) generating the imports + shims from uniffi metadata in the
//! transformer (Option 2). Both are in T0.C.7.C / T0.C.7.D scope. Until
//! then, this shim builds and produces correct table indices for
//! Rust-side `call_indirect` — but a JS host that wires the imports with
//! their real signatures will fail instantiation against the elided ones.

/// Universal callback ABI shape used to take the address of every Rust
/// import. The actual signature each Kotlin `@JsExport` declares varies by
/// method (different arg counts, different RustBuffer ptr/cap/len triples),
/// but for the purpose of `__indirect_function_table` placement we only need
/// SOMETHING that takes `&` of each function. Casting to a single shape
/// keeps the static array homogeneous; runtime only ever reads the table
/// index, never invokes through the cast pointer. See module docstring on
/// the cascading signature-mismatch gap.
type CallbackFn = unsafe extern "C" fn();

// Imports from the Kotlin/Wasm `@JsExport` shims under the well-known
// `gobley_callbacks` module name. The JS shim layer
// (`crates/gobley-wasm-transformer/src/templates/wasmjs_helpers.mjs`) wires
// each of these to the matching `gobley_callback_*` Kotlin function.
//
// Argument lists are intentionally elided (`fn name()`) — see module docstring
// for the trade-off and the T0.C.7.C / T0.C.7.D follow-up that resolves it.
#[link(wasm_import_module = "gobley_callbacks")]
extern "C" {
    // Getters trait — order from coverall.udl:254 (Trait, WithForeign).
    fn gobley_callback_Getters_getBool();
    fn gobley_callback_Getters_getString();
    fn gobley_callback_Getters_getOption();
    fn gobley_callback_Getters_getList();
    fn gobley_callback_Getters_getNothing();
    fn gobley_callback_Getters_roundTripObject();
    fn gobley_callback_Getters_uniffi_free();

    // NodeTrait — order from coverall.udl:269 (Trait, WithForeign).
    fn gobley_callback_NodeTrait_name();
    fn gobley_callback_NodeTrait_setParent();
    fn gobley_callback_NodeTrait_getParent();
    fn gobley_callback_NodeTrait_strongCount();
    fn gobley_callback_NodeTrait_uniffi_free();
}

/// Force wasm-ld to materialise function-table indices for every `Getters`
/// import. `#[used]` suppresses dead-code elimination so the static stays
/// alive even though nothing in Rust actually invokes through these pointers.
/// Pattern adopted from the T0.C.1 spike at
/// `crates/gobley-wasm-vtable-spike/src/lib.rs:64-65`.
#[used]
static CALLBACKS_GETTERS: [CallbackFn; 7] = [
    gobley_callback_Getters_getBool as CallbackFn,
    gobley_callback_Getters_getString as CallbackFn,
    gobley_callback_Getters_getOption as CallbackFn,
    gobley_callback_Getters_getList as CallbackFn,
    gobley_callback_Getters_getNothing as CallbackFn,
    gobley_callback_Getters_roundTripObject as CallbackFn,
    gobley_callback_Getters_uniffi_free as CallbackFn,
];

#[used]
static CALLBACKS_NODE_TRAIT: [CallbackFn; 5] = [
    gobley_callback_NodeTrait_name as CallbackFn,
    gobley_callback_NodeTrait_setParent as CallbackFn,
    gobley_callback_NodeTrait_getParent as CallbackFn,
    gobley_callback_NodeTrait_strongCount as CallbackFn,
    gobley_callback_NodeTrait_uniffi_free as CallbackFn,
];

/// Resolve the `__indirect_function_table` index of the Nth `Getters` vtable
/// slot. Indices `0..6` are the trait methods in UDL order; index `6` is
/// `uniffi_free`. The `as u32` truncation is sound on wasm32 (function
/// pointers are 32-bit table indices by spec — see
/// `crates/gobley-wasm-vtable-spike/src/lib.rs:73-81`).
///
/// Returns `u32::MAX` for out-of-range method ids — Kotlin shouldn't ask
/// for those, but defensive bounds-checking beats a UB panic in the JS
/// console.
#[no_mangle]
pub extern "C" fn uniffi_coverall_callback_Getters_vtable_index(method: u32) -> u32 {
    let idx = method as usize;
    if idx >= CALLBACKS_GETTERS.len() {
        return u32::MAX;
    }
    CALLBACKS_GETTERS[idx] as usize as u32
}

#[no_mangle]
pub extern "C" fn uniffi_coverall_callback_NodeTrait_vtable_index(method: u32) -> u32 {
    let idx = method as usize;
    if idx >= CALLBACKS_NODE_TRAIT.len() {
        return u32::MAX;
    }
    CALLBACKS_NODE_TRAIT[idx] as usize as u32
}
