//! Per-interface `vtable_index` Rust shim — fixture-specific stop-gap (T0.C.7).
//!
//! Why this file exists:
//! Upstream uniffi 0.29.5 does NOT emit per-callback-interface
//! `uniffi_<ns>_callback_<iface>_vtable_index(method) -> u32` exports. The
//! Kotlin/Wasm binding template
//! (`crates/gobley-uniffi-bindgen/src/templates/wasm-js/CallbackInterfaceImpl.kt`)
//! declares one `external fun __gobley_vtable_index_<iface>(method: Int): Int`
//! per callback interface and routes it through `globalThis.__gobleyRustExports`.
//! Without this shim crate side-loaded into the cdylib, those Kotlin externals
//! resolve to `undefined` at runtime and the first callback dispatch traps.
//!
//! Long-term plan (NOT this commit): synthesize these exports in
//! `gobley-wasm-transformer` post-process by walking the
//! `gobley_callbacks.<name>` import section. That makes the bindings work for
//! any consumer crate without per-fixture hand-written Rust. The hand-written
//! shim here proves the pipeline shape works end-to-end against the coverall
//! fixture. Tracked in `crates/gobley-uniffi-bindgen/docs/T0-kotlin-wasm-design.md`
//! Decision 3.
//!
//! Constraints baked into this file:
//!   * Gating happens at the `mod wasm_vtable_shim;` site in `lib.rs` via
//!     `#[cfg(target_arch = "wasm32")]`. JVM/Native cdylib builds therefore
//!     never see these symbols (linker would fail to resolve the
//!     `gobley_callbacks.*` imports — those only exist in the wasm world).
//!     A redundant inner `#![cfg(...)]` would warn under
//!     `clippy::duplicated_attributes`; we rely on the parent module's gate
//!     alone.
//!   * Method order MUST match the Kotlin template's `vtable_methods.iter()`
//!     iteration order, which mirrors UDL declaration order. uniffi's
//!     `CallbackInterface::vtable_methods()` walks `methods()` in source order
//!     (see `uniffi_bindgen-0.29.5/src/interface/callbacks.rs`). For
//!     `Getters` and `NodeTrait` the UDL order is fixed at
//!     `tests/uniffi/coverall/src/coverall.udl:254` and `:269`. Note: the
//!     emitted `@JsExport` block iterates in alphabetical-on-Kotlin-name
//!     order, which is independent — what matters here is the address-taking
//!     order in the `vtable_index` match arms, which IS UDL source order.
//!   * Method index `methods.len()` is reserved for `uniffi_free` (see
//!     `CallbackInterfaceImpl.kt`'s `register()` implementation).
//!   * `extern "C" fn` items are placed in `__indirect_function_table` by
//!     wasm-ld only if their address is observed somewhere in reachable code
//!     (T0.C.1 spike, "Surprise: linker reorders imports" — see
//!     `crates/gobley-wasm-vtable-spike/src/lib.rs:64-65`). The `as usize`
//!     casts inside the `#[no_mangle] pub extern "C" fn …vtable_index` match
//!     arms below serve that role: each cast lowers to an `i32.const
//!     <table_index>` (linker-relocated) inside an exported, non-DCE'd
//!     function. The vtable index returned to Kotlin is therefore the same
//!     table slot Rust would `call_indirect` against — the wasm engine then
//!     dispatches into the host-provided Kotlin `@JsExport` function.
//!
//! Why hand-written rather than generated by `build.rs`:
//! `build.rs` would need to parse the UDL or read uniffi metadata to discover
//! the callback interfaces. That's the same engineering as Option 2 (proper
//! transformer-based synthesis) without the cross-fixture payoff. We pay the
//! per-fixture cost only here, only for T0.C.7's verification gate.
//!
//! T0.C.7.B.1: full per-method ABI signatures.
//! Each `extern "C"` import below now mirrors the corresponding Kotlin
//! `@JsExport public fun gobley_callback_*` parameter list. The wasm engine
//! validates each import's declared type against the host-provided function
//! at JS instantiation time; mismatched arity or types produce a wasm
//! link-error before any Rust code runs. Source of truth for the signatures:
//! the wasmJs Kotlin output emitted by `crates/gobley-uniffi-bindgen` for
//! coverall (regenerate with the bindgen `--library` flag against
//! `libgobley_fixture_coverall.dylib` and a temp `uniffi.toml` enabling
//! `kotlin_targets = ["wasmJs"]`).
//!
//! UniFFI ABI conventions captured here (per the Kotlin template
//! `crates/gobley-uniffi-bindgen/src/templates/wasm-js/CallbackInterfaceImpl.kt`):
//!   * `uniffi_handle: u64` is always the first parameter (Kotlin `Long`).
//!   * `RustBuffer`-typed args flatten to `(capacity: i32, len: i32, data: i32)`
//!     — the Kotlin emitter uses suffix-named `<arg>Capacity`, `<arg>Len`,
//!     `<arg>Data` for that triple. This is the wasm32 lowering of the
//!     by-value `RustBufferByValue` data class.
//!   * Primitive return uses an out-pointer named `uniffi_out_return_ptr: i32`
//!     (Kotlin `uniffiOutReturnPtr: Pointer`, Pointer = Int). Type of the
//!     out is implicit — Rust just sees the `i32` address.
//!   * `RustBuffer` return uses the same single `uniffi_out_return_ptr: i32`
//!     out-pointer (NOT the flattened triple — only by-value RustBuffer ARG
//!     positions get flattened; the out-pointer for a RustBuffer return is
//!     a single pointer to a RustBuffer struct in Rust linear memory).
//!   * Void return still has an `uniffi_out_return_ptr: i32` (Kotlin
//!     dispatcher writes `Unit` to satisfy the trait shape).
//!   * `uniffi_call_status_ptr: i32` is always last for non-async methods.
//!     Wraps `*mut UniffiRustCallStatus` (i8 code + RustBuffer error_buf).
//!   * `uniffi_free(handle: u64)` is the per-interface destructor — last
//!     vtable slot, no out-pointer or call-status.
//!   * `Arc<T>` interface args travel as raw `i32` pointers (Kotlin `Pointer?`).
//!   * No async methods in coverall's callback interfaces (verified against
//!     `tests/uniffi/coverall/src/commonMain/rust/traits.rs`); if any UDL
//!     gets `async`, the corresponding shim will need a foreign-future
//!     continuation parameter — see uniffi's `FfiCallbackFunction` async
//!     branch.
//!
//! Wire-type widening note: wasm core has no `i8` value type. `extern "C"
//! fn(x: i8)` lowers to `(param i32)` per the wasm32-unknown-unknown C ABI;
//! the Kotlin/Wasm side widens `Byte` → i32 the same way. So declaring `i8`
//! on the Rust side and `Byte` on the Kotlin side produces the same wire
//! signature, and the type annotations carry semantic intent (bool / byte
//! enum) for the human reader.
//!
//! Why not a homogeneous `[CallbackFn; N]` static array (T0.C.7.B pre-image):
//! Once each import has its true per-method signature, casting each one to a
//! single `unsafe extern "C" fn()` shape via `as` is rejected by rustc
//! (`E0605: non-primitive cast`). Casting through `usize` at static-init time
//! is also rejected (`pointers do not have an integer value at compile-time`).
//! `mem::transmute` between fn-pointers of different signatures is not const.
//! The fix: drop the homogeneous arrays and observe each address inline in
//! the `vtable_index` `match` body — the address-take is still in reachable
//! exported code, so wasm-ld places the import in the function table just
//! the same. We lose the static `len()` check; the bounds-check is now an
//! explicit `_` arm returning `u32::MAX`.

// Imports from the Kotlin/Wasm `@JsExport` shims under the well-known
// `gobley_callbacks` module name. The JS shim layer
// (`crates/gobley-wasm-transformer/src/templates/wasmjs_helpers.mjs`) wires
// each of these to the matching `gobley_callback_*` Kotlin function.
//
// Per-method signatures mirror the Kotlin `@JsExport` parameter lists
// byte-for-byte so the wasm engine accepts the imports at instantiation
// time. See module docstring for the ABI conventions and the source of
// truth (regenerate the wasmJs Kotlin output to verify after any UDL or
// bindgen change).
#[link(wasm_import_module = "gobley_callbacks")]
extern "C" {
    // ---- Getters trait — UDL order from coverall.udl:254 ----------------

    // boolean get_bool(boolean v, boolean arg2)
    fn gobley_callback_Getters_getBool(
        uniffi_handle: u64,
        v: i8,
        arg2: i8,
        uniffi_out_return_ptr: i32,
        uniffi_call_status_ptr: i32,
    );

    // [Throws=CoverallError] string get_string(string v, boolean arg2)
    // RustBuffer arg `v` flattens to (capacity, len, data); RustBuffer return
    // travels via the single `uniffi_out_return_ptr`.
    fn gobley_callback_Getters_getString(
        uniffi_handle: u64,
        v_capacity: i32,
        v_len: i32,
        v_data: i32,
        arg2: i8,
        uniffi_out_return_ptr: i32,
        uniffi_call_status_ptr: i32,
    );

    // [Throws=ComplexError] string? get_option(string v, boolean arg2)
    fn gobley_callback_Getters_getOption(
        uniffi_handle: u64,
        v_capacity: i32,
        v_len: i32,
        v_data: i32,
        arg2: i8,
        uniffi_out_return_ptr: i32,
        uniffi_call_status_ptr: i32,
    );

    // sequence<i32> get_list(sequence<i32> v, boolean arg2)
    fn gobley_callback_Getters_getList(
        uniffi_handle: u64,
        v_capacity: i32,
        v_len: i32,
        v_data: i32,
        arg2: i8,
        uniffi_out_return_ptr: i32,
        uniffi_call_status_ptr: i32,
    );

    // void get_nothing(string v)
    // Void return: Kotlin dispatcher still receives `uniffiOutReturnPtr` and
    // writes `Unit` — matching pointer presence preserved on the Rust side.
    fn gobley_callback_Getters_getNothing(
        uniffi_handle: u64,
        v_capacity: i32,
        v_len: i32,
        v_data: i32,
        uniffi_out_return_ptr: i32,
        uniffi_call_status_ptr: i32,
    );

    // Coveralls round_trip_object(Coveralls coveralls)
    // Arc<T> interface args travel as raw i32 pointers (Kotlin `Pointer?`).
    fn gobley_callback_Getters_roundTripObject(
        uniffi_handle: u64,
        coveralls: i32,
        uniffi_out_return_ptr: i32,
        uniffi_call_status_ptr: i32,
    );

    // Per-interface destructor — last vtable slot.
    fn gobley_callback_Getters_uniffi_free(handle: u64);

    // ---- NodeTrait — UDL order from coverall.udl:269 --------------------

    // string name()
    fn gobley_callback_NodeTrait_name(
        uniffi_handle: u64,
        uniffi_out_return_ptr: i32,
        uniffi_call_status_ptr: i32,
    );

    // void set_parent(NodeTrait? parent)
    // `NodeTrait?` (nullable trait object) lowers to RustBuffer (Option-of-Arc
    // is wrapped in a RustBuffer per uniffi's optional-interface ABI), so the
    // arg flattens to the (capacity, len, data) triple.
    fn gobley_callback_NodeTrait_setParent(
        uniffi_handle: u64,
        parent_capacity: i32,
        parent_len: i32,
        parent_data: i32,
        uniffi_out_return_ptr: i32,
        uniffi_call_status_ptr: i32,
    );

    // NodeTrait? get_parent()
    // RustBuffer return uses the single out-pointer (NOT a triple).
    fn gobley_callback_NodeTrait_getParent(
        uniffi_handle: u64,
        uniffi_out_return_ptr: i32,
        uniffi_call_status_ptr: i32,
    );

    // [Self=ByArc] u64 strong_count()
    fn gobley_callback_NodeTrait_strongCount(
        uniffi_handle: u64,
        uniffi_out_return_ptr: i32,
        uniffi_call_status_ptr: i32,
    );

    fn gobley_callback_NodeTrait_uniffi_free(handle: u64);
}

/// Resolve the `__indirect_function_table` index of the Nth `Getters` vtable
/// slot. Indices `0..6` are the trait methods in UDL order; index `6` is
/// `uniffi_free`. The `as u32` truncation is sound on wasm32 (function
/// pointers are 32-bit table indices by spec — see
/// `crates/gobley-wasm-vtable-spike/src/lib.rs:73-81`).
///
/// Returns `u32::MAX` for out-of-range method ids — Kotlin shouldn't ask
/// for those, but defensive bounds-checking beats a UB panic in the JS
/// console.
///
/// The inline `as usize` casts also serve as the address-take that forces
/// wasm-ld to materialise each import into `__indirect_function_table` — see
/// the module docstring "Why not a homogeneous static array" note for the
/// reason this doesn't use a `[CallbackFn; N]`.
#[no_mangle]
pub extern "C" fn uniffi_coverall_callback_Getters_vtable_index(method: u32) -> u32 {
    let addr: usize = match method {
        0 => gobley_callback_Getters_getBool as usize,
        1 => gobley_callback_Getters_getString as usize,
        2 => gobley_callback_Getters_getOption as usize,
        3 => gobley_callback_Getters_getList as usize,
        4 => gobley_callback_Getters_getNothing as usize,
        5 => gobley_callback_Getters_roundTripObject as usize,
        6 => gobley_callback_Getters_uniffi_free as usize,
        _ => return u32::MAX,
    };
    addr as u32
}

#[no_mangle]
pub extern "C" fn uniffi_coverall_callback_NodeTrait_vtable_index(method: u32) -> u32 {
    let addr: usize = match method {
        0 => gobley_callback_NodeTrait_name as usize,
        1 => gobley_callback_NodeTrait_setParent as usize,
        2 => gobley_callback_NodeTrait_getParent as usize,
        3 => gobley_callback_NodeTrait_strongCount as usize,
        4 => gobley_callback_NodeTrait_uniffi_free as usize,
        _ => return u32::MAX,
    };
    addr as u32
}
