// Generated by gobley-wasm-transformer (T0.C.6).
//
// Kotlin/Wasm <-> Rust/Wasm host bridge for the `{{ crate_name }}` crate.
//
// Two-WASM-module memory model (T0.B Decision 1, T0.C.6):
//   * Rust runs in `wasm32-unknown-unknown` linear-memory mode and owns
//     its own `WebAssembly.Memory`.
//   * Kotlin runs in Wasm-GC mode and owns a separate, JS-managed object
//     graph.
//   * This file is the only host-side bridge: it instantiates the Rust
//     module, exposes its exports as `globalThis.__gobleyRustExports`,
//     and exposes a memory-growth-safe `DataView` over Rust linear memory
//     as `globalThis.__gobleyWasmMemory`.
//
// The Kotlin templates rely on those globals through `@JsFun` bodies
// (see `wasm-js/PointerHelper.kt` and `wasm-js/CallbackInterfaceImpl.kt`).
// This shim does NOT re-declare those primitive accessors — the inline
// JS bodies on the Kotlin side already do. We only handle bootstrap +
// callback wiring + memory-growth re-acquisition.

const KOTLIN_CALLBACK_EXPORTS = [
{%- for name in kotlin_callback_exports() %}
    "{{ name }}",
{%- endfor %}
];

const RUST_IMPORTS_TO_BIND = [
{%- for binding in rust_callback_imports() %}
    { module: "{{ binding.module }}", name: "{{ binding.name }}" },
{%- endfor %}
];

/**
 * Refresh `globalThis.__gobleyWasmMemory` to a fresh `DataView` over
 * the current Rust linear memory buffer. Memory growth invalidates the
 * underlying `ArrayBuffer`, so the Kotlin `@JsFun` accessors expect a
 * fresh `DataView` per primitive call. We wrap the `DataView` itself,
 * not the `Memory`, because the inline accessors call `.getInt32(...)`
 * straight off the global.
 *
 * Production hot paths re-acquire on every primitive read/write, which
 * dominates the JIT optimization. The fast-path here is `if buffer
 * unchanged: reuse cached DataView`.
 */
function gobleyInstallMemoryView(memory) {
    let cachedBuffer = null;
    let cachedView = null;
    Object.defineProperty(globalThis, "__gobleyWasmMemory", {
        configurable: true,
        get() {
            const buffer = memory.buffer;
            if (buffer !== cachedBuffer) {
                cachedBuffer = buffer;
                cachedView = new DataView(buffer);
            }
            return cachedView;
        },
    });
}

/**
 * Resolve the Kotlin/Wasm-emitted `@JsExport` callback functions.
 *
 * Kotlin/Wasm 2.0+ surfaces `@JsExport public fun foo(...)` declarations
 * as named exports on the Kotlin/Wasm JS module. The host Kotlin app
 * passes that module (or a subset of it) to `init` so we can route Rust
 * `call_indirect` dispatches into Kotlin user code.
 *
 * Resolution order, first hit wins:
 *   1. Caller-supplied `kotlinExports` argument (most explicit).
 *   2. `globalThis.__gobleyKotlinExports` (set by an embedder before init).
 *   3. `globalThis` itself (for legacy / browser-direct loads where
 *      Kotlin/Wasm hoists @JsExport names to window scope).
 *
 * Throws if any required symbol is missing — silent miss would manifest
 * as a Rust-side `RuntimeError: indirect call signature mismatch` at the
 * first user callback, which is harder to diagnose.
 */
function gobleyResolveKotlinExports(kotlinExports) {
    const candidates = [
        kotlinExports,
        globalThis.__gobleyKotlinExports,
        globalThis,
    ].filter((c) => c != null);
    const resolved = {};
    const missing = [];
    for (const name of KOTLIN_CALLBACK_EXPORTS) {
        let fn = null;
        for (const candidate of candidates) {
            const found = candidate[name];
            if (typeof found === "function") {
                fn = found;
                break;
            }
        }
        if (fn === null) {
            missing.push(name);
        } else {
            resolved[name] = fn;
        }
    }
    if (missing.length > 0) {
        throw new Error(
            "gobley wasmJs shim: missing Kotlin @JsExport callbacks: " +
                missing.join(", ") +
                ". Pass them via init({ kotlinExports }) or set globalThis.__gobleyKotlinExports.",
        );
    }
    return resolved;
}

/**
 * Build the import dictionary for `WebAssembly.instantiate`.
 *
 * Each entry in `RUST_IMPORTS_TO_BIND` corresponds to a host import the
 * Rust module declared via `extern "C"` (uniffi's vtable callback names
 * follow `uniffi_<ns>_callback_<iface>_<method>` — but we don't bake
 * that convention in: the transformer reads the actual import section).
 * We bind each to the matching Kotlin `@JsExport` function. Both the
 * Rust import name and the Kotlin export name share the same suffix
 * after the well-known `gobley_callback_` / `gobley_async_` prefix; if
 * the convention drifts, edit `rust_callback_imports()` /
 * `kotlin_callback_exports()` in `lib.rs` to keep them aligned.
 */
function gobleyBuildRustImports(kotlinFns) {
    const imports = {};
    for (const { module, name } of RUST_IMPORTS_TO_BIND) {
        if (!Object.prototype.hasOwnProperty.call(imports, module)) {
            imports[module] = {};
        }
        const kotlinFn = kotlinFns[name];
        if (typeof kotlinFn !== "function") {
            throw new Error(
                "gobley wasmJs shim: cannot bind Rust import " +
                    module + "." + name +
                    " — no matching Kotlin @JsExport function.",
            );
        }
        imports[module][name] = kotlinFn;
    }
    return imports;
}

/**
 * Async-instantiate the Rust WASM module and wire up the host bridge.
 *
 * @param {BufferSource | Response | Promise<Response>} rustWasm  Bytes,
 *   `Response`, or a `Promise<Response>` for the Rust cdylib.
 * @param {Object} [opts]
 * @param {Object} [opts.kotlinExports]  Module-like object whose own
 *   properties include the Kotlin `@JsExport` callback functions
 *   listed in `KOTLIN_CALLBACK_EXPORTS`. Optional if
 *   `globalThis.__gobleyKotlinExports` is set instead.
 * @param {Object} [opts.additionalImports]  Extra import modules merged
 *   into the dictionary handed to `WebAssembly.instantiate`. Useful for
 *   user-defined `extern "C"` blocks beyond the gobley-generated ones.
 * @returns {Promise<WebAssembly.Instance>}  The Rust instance. Also
 *   stored at `globalThis.__gobleyRustExports` for inline `@JsFun`
 *   bodies (see `wasm-js/CallbackInterfaceImpl.kt`).
 */

{%- for (name, expr) in wasm_bindgen_factories() %}
const {{ name }} = {{ expr }};
{%- endfor %}

function gobleyRunCjsFactory(factory) {
    const mod = { exports: {} };
    factory(function require() { throw new Error("gobley: require() not supported in wasmJs"); }, mod, mod.exports);
    return mod.exports;
}

const WASM_BINDGEN_MODULES = {
{%- for module_name in wasm_bindgen_module_names() %}
    "{{ module_name }}": (() => {
        const idx = {{ loop.index0 }};
        const factories = [
            {%- for (name, _) in wasm_bindgen_factories() %}
            {{ name }},
            {%- endfor %}
        ];
        return idx < factories.length ? gobleyRunCjsFactory(factories[idx]) : {};
    })(),
{%- endfor %}
};

export async function init(rustWasm, opts) {
    const options = opts || {};
    const kotlinFns = gobleyResolveKotlinExports(options.kotlinExports);
    const rustImports = gobleyBuildRustImports(kotlinFns);

    // Merge wasm-bindgen module imports
    for (const [moduleName, moduleObj] of Object.entries(WASM_BINDGEN_MODULES)) {
        rustImports[moduleName] = Object.assign(
            rustImports[moduleName] || {},
            moduleObj,
        );
    }

    if (options.additionalImports) {
        for (const moduleName of Object.keys(options.additionalImports)) {
            const existing = rustImports[moduleName] || {};
            rustImports[moduleName] = Object.assign(
                existing,
                options.additionalImports[moduleName],
            );
        }
    }

    let result;
    if (rustWasm && typeof rustWasm.then === "function") {
        result = await WebAssembly.instantiateStreaming(rustWasm, rustImports);
    } else if (typeof Response !== "undefined" && rustWasm instanceof Response) {
        result = await WebAssembly.instantiateStreaming(rustWasm, rustImports);
    } else {
        result = await WebAssembly.instantiate(rustWasm, rustImports);
    }

    const instance = result.instance || result;
    const exports = instance.exports;

    if (!exports.memory || !(exports.memory instanceof WebAssembly.Memory)) {
        throw new Error(
            "gobley wasmJs shim: Rust module does not export `memory`. " +
                "Ensure the cdylib is built with the standard wasm32 toolchain.",
        );
    }

    gobleyInstallMemoryView(exports.memory);
    globalThis.__gobleyRustExports = exports;
    globalThis.__gobleyKotlinExports = kotlinFns;

    // Bind wasm instance to wasm-bindgen JS modules.
    // The wasm-bindgen factory exports __wbg_set_wasm which lets the
    // JS glue functions access wasm memory and exports.
    for (const moduleObj of Object.values(WASM_BINDGEN_MODULES)) {
        if (typeof moduleObj.__wbg_set_wasm === "function") {
            moduleObj.__wbg_set_wasm(exports);
        }
        if (typeof moduleObj.__wbindgen_init_externref_table === "function") {
            moduleObj.__wbindgen_init_externref_table();
        }
    }

    // Surface `__indirect_function_table` for callback dispatch and
    // runtime registration of Kotlin @JsExport functions.
    const table = exports.__indirect_function_table;
    if (table instanceof WebAssembly.Table) {
        globalThis.__gobleyIndirectFunctionTable = table;
    }

    return instance;
}

/**
 * Register a JS function into the Rust module's indirect function table.
 * Returns the table index that can be passed to Rust's `call_indirect`.
 * Used by Kotlin/Wasm to register @JsExport callbacks (e.g. async
 * continuation callback) into the Rust function table at runtime.
 */
export function registerInTable(fn_) {
    const table = globalThis.__gobleyIndirectFunctionTable;
    if (!table) {
        throw new Error("gobley: __indirect_function_table not available — init() not called?");
    }
    const idx = table.grow(1);
    table.set(idx, fn_);
    return idx;
}

/**
 * Read a slice of Rust linear memory as a `Uint8Array`. Convenience for
 * embedders that want to inspect a `RustBuffer` payload outside of the
 * Kotlin layer (e.g. logging, debugging). Hot-path Kotlin code uses the
 * inline `@JsFun` byte accessors instead — they're cheaper.
 */
export function readBytes(ptr, len) {
    const buffer = globalThis.__gobleyWasmMemory.buffer;
    return new Uint8Array(buffer, ptr, len);
}

/**
 * Write a `Uint8Array` into Rust linear memory at `ptr`. Same caveat as
 * `readBytes`: hot-path Kotlin uses the inline accessors. This is for
 * embedders that want to splice a buffer in directly (e.g. JS-side I/O
 * handing payload to a Rust parser).
 */
export function writeBytes(ptr, bytes) {
    const buffer = globalThis.__gobleyWasmMemory.buffer;
    new Uint8Array(buffer, ptr, bytes.length).set(bytes);
}
