@file:Suppress("ClassName", "Unused", "RemoveRedundantBackticks", "PropertyName")

{% if let Some(package_name) = package_name -%}
package {{ package_name }}

{% endif -%}

// Generated by gobley-wasm-transformer (T0.C.6.b — KotlinWasmJsRenderer).
//
// Kotlin/Wasm-compatible counterpart to the Kotlin/JS file emitted by
// `KotlinJsRenderer`. The two renderers consume the same input WASM
// module but differ in what they expose to the host:
//
//   * Kotlin/JS path (js.kt) — emits a self-contained loader: external
//     `WebAssembly` class hierarchy, base64-decode helpers, an
//     instance-creating `createInstance(...)` function, and per-module
//     import structures with `tblIdx_<name>` constants.
//
//   * Kotlin/Wasm path (this file) — emits **only** the raw bytes plus
//     a small set of helpers callable from Kotlin/Wasm. Actual
//     `WebAssembly.instantiate` happens on the JavaScript side via the
//     `gobley_<crate>_wasmjs_helpers.mjs` shim (also emitted by this
//     transformer; see `KotlinWasmJsHelpersRenderer`). The bindgen-emitted
//     `wasm-js/NamespaceLibraryTemplate.kt` wires `UniffiLib` to those
//     bytes through `init(...)` once T0.C.3.b lands.
//
// Why two outputs and not a shared one: Kotlin/Wasm forbids the legacy
// Kotlin/JS interop surface that the JS path depends on:
//
//   * `kotlin.Any` parameters in `external fun` declarations.
//   * `org.khronos.webgl.ArrayBuffer` (Kotlin/JS-only legacy IR class).
//   * Nested classes inside interfaces / external classes.
//   * `dynamic` (does not exist in Kotlin/Wasm).
//
// Therefore this template emits **no** `WebAssembly.*` external class,
// no `RustWebAssemblyImports`, no `RustWebAssemblyExports`, no
// `createInstance(...)`. The .mjs shim owns instantiation; the Kotlin
// side just hands over the bytes.

// Base64-encoded Rust `wasm32-unknown-unknown` cdylib bytes. Kept in grouped
// chunks because Kotlin/Wasm can crash while lowering very large string
// literals or very large fixed-array initializers. Decoded by the host before
// passing into `init(...)` from the .mjs shim. Identical payload to the
// Kotlin/JS `BASE64` constant — same upstream WASM module after
// `Transformer::transform()` (stack-pointer shim, function imports, optional
// wasm-bindgen rewrites).
private val GOBLEY_WASM_BASE64_CHUNK_GROUPS: Array<Array<String>> = arrayOf(
{%- for group in base64_chunk_groups() %}
    arrayOf(
    {%- for chunk in group %}
        "{{ chunk }}"{% if !loop.last %},{% endif %}
    {%- endfor %}
    ){% if !loop.last %},{% endif %}
{%- endfor %}
)

internal val GOBLEY_WASM_BASE64: String
    get() = buildString {
        for (group in GOBLEY_WASM_BASE64_CHUNK_GROUPS) {
            for (chunk in group) {
                append(chunk)
            }
        }
    }

// Convenience accessor: decode the embedded WASM cdylib to a `ByteArray`.
//
// Kotlin/Wasm 2.1.10's stdlib does not provide `kotlin.io.encoding.Base64`
// for the wasmJs target (it is JVM/Native-only as of 2.1). We therefore
// implement the four-char-to-three-byte decode inline. The encoded
// payload is well-formed (emitted by `BASE64_STANDARD.encode` in
// `Transformer::render_into_wasmjs_kt`) so we don't bother with strict
// validation — malformed input would mean a transformer bug, not a
// runtime user error.
//
// Returns the raw bytes ready to feed into the .mjs shim's
// `init(rustWasm, opts)` entry point. The host is responsible for
// converting `ByteArray` to `Uint8Array`/`ArrayBuffer` per the JS interop
// dance — this differs across Kotlin/Wasm versions and we intentionally
// don't bake the conversion in here.
internal fun gobleyWasmBytes(): ByteArray {
    return gobleyDecodeBase64(GOBLEY_WASM_BASE64_CHUNK_GROUPS)
}

private fun gobleyDecodeBase64(chunkGroups: Array<Array<String>>): ByteArray {
    val inputLen = gobleyBase64Length(chunkGroups)

    var padding = 0
    val lastChunk = gobleyLastBase64Chunk(chunkGroups)
    if (lastChunk.isNotEmpty()) {
        if (lastChunk.endsWith("==")) {
            padding = 2
        } else if (lastChunk.endsWith("=")) {
            padding = 1
        }
    }
    val outputLen = (inputLen * 3 / 4) - padding
    val output = ByteArray(outputLen)

    var outIdx = 0
    var buffer = 0
    var bufferBits = 0

    for (group in chunkGroups) {
        for (chunk in group) {
            for (inIdx in 0 until chunk.length) {
                val c = chunk[inIdx]
                if (c == '=') {
                    // Padding terminates the stream; remaining buffer bits are
                    // zero by construction for valid base64 input.
                    return output
                }
                val v = gobleyBase64CharValue(c)
                if (v < 0) {
                    // Tolerate whitespace silently — base64 producers may wrap.
                    continue
                }
                buffer = (buffer shl 6) or v
                bufferBits += 6
                if (bufferBits >= 8) {
                    bufferBits -= 8
                    output[outIdx] = ((buffer ushr bufferBits) and 0xFF).toByte()
                    outIdx++
                }
            }
        }
    }

    return output
}

private fun gobleyBase64Length(chunkGroups: Array<Array<String>>): Int {
    var length = 0
    for (group in chunkGroups) {
        for (chunk in group) {
            length += chunk.length
        }
    }
    return length
}

private fun gobleyLastBase64Chunk(chunkGroups: Array<Array<String>>): String {
    for (groupIndex in chunkGroups.lastIndex downTo 0) {
        val group = chunkGroups[groupIndex]
        if (group.isNotEmpty()) {
            return group[group.lastIndex]
        }
    }
    return ""
}

private fun gobleyBase64CharValue(c: Char): Int {
    return when (c) {
        in 'A'..'Z' -> c.code - 'A'.code
        in 'a'..'z' -> c.code - 'a'.code + 26
        in '0'..'9' -> c.code - '0'.code + 52
        '+' -> 62
        '/' -> 63
        else -> -1
    }
}
